package io.jpress.module.route.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTRoute<M extends BaseTRoute<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSupplierId(java.lang.Long supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Long getSupplierId() {
		return getLong("supplier_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setCode(java.lang.Long code) {
		set("code", code);
	}
	
	public java.lang.Long getCode() {
		return getLong("code");
	}

	public void setEditMode(java.lang.String editMode) {
		set("edit_mode", editMode);
	}

	public java.lang.String getEditMode() {
		return getStr("edit_mode");
	}

	public void setSlug(java.lang.String slug) {
		set("slug", slug);
	}

	public java.lang.String getSlug() {
		return getStr("slug");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setTotalDays(java.lang.Integer totalDays) {
		set("total_days", totalDays);
	}
	
	public java.lang.Integer getTotalDays() {
		return getInt("total_days");
	}

	public void setTheme(java.lang.String theme) {
		set("theme", theme);
	}
	
	public java.lang.String getTheme() {
		return getStr("theme");
	}

	public void setLeaveCity(java.lang.String leaveCity) {
		set("leave_city", leaveCity);
	}
	
	public java.lang.String getLeaveCity() {
		return getStr("leave_city");
	}

	public void setDestCity(java.lang.String destCity) {
		set("dest_city", destCity);
	}
	
	public java.lang.String getDestCity() {
		return getStr("dest_city");
	}

	public void setDepartureDate(java.util.Date departureDate) {
		set("departure_date", departureDate);
	}
	
	public java.util.Date getDepartureDate() {
		return get("departure_date");
	}

	public void setExpireDate(java.util.Date expireDate) {
		set("expire_date", expireDate);
	}
	
	public java.util.Date getExpireDate() {
		return get("expire_date");
	}

	public void setRouteSource(java.lang.String routeSource) {
		set("route_source", routeSource);
	}
	
	public java.lang.String getRouteSource() {
		return getStr("route_source");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}
	
	public java.lang.String getStyle() {
		return getStr("style");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}
	
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public void setThumbnailListStore(java.lang.String thumbnailListStore) {
		set("thumbnail_list_store", thumbnailListStore);
	}
	
	public java.lang.String getThumbnailListStore() {
		return getStr("thumbnail_list_store");
	}

	public void setQrcode(java.lang.String qrcode) {
		set("qrcode", qrcode);
	}
	
	public java.lang.String getQrcode() {
		return getStr("qrcode");
	}

	public void setCost(java.lang.Integer cost) {
		set("cost", cost);
	}
	
	public java.lang.Integer getCost() {
		return getInt("cost");
	}

	public void setMarketPrice(java.lang.Integer marketPrice) {
		set("market_price", marketPrice);
	}
	
	public java.lang.Integer getMarketPrice() {
		return getInt("market_price");
	}

	public void setPrice(java.lang.Integer price) {
		set("price", price);
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public void setChildPrice(java.lang.Integer childPrice) {
		set("child_price", childPrice);
	}
	
	public java.lang.Integer getChildPrice() {
		return getInt("child_price");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setGroupNum(java.lang.Integer groupNum) {
		set("group_num", groupNum);
	}
	
	public java.lang.Integer getGroupNum() {
		return getInt("group_num");
	}

	public void setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}

	public void setGroupCycle(java.lang.String groupCycle) {
		set("group_cycle", groupCycle);
	}

	public java.lang.String getGroupCycle() {
		return getStr("group_cycle");
	}

	public void setCommentStatus(java.lang.Boolean commentStatus) {
		set("comment_status", commentStatus);
	}
	
	public java.lang.Boolean getCommentStatus() {
		return getBoolean("comment_status");
	}

	public void setCommentCount(java.lang.Integer commentCount) {
		set("comment_count", commentCount);
	}
	
	public java.lang.Integer getCommentCount() {
		return getInt("comment_count");
	}

	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}
	
	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	public void setViewCount(java.lang.Integer viewCount) {
		set("view_count", viewCount);
	}
	
	public java.lang.Integer getViewCount() {
		return getInt("view_count");
	}

	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}
	
	public java.lang.String getMetaKeywords() {
		return getStr("meta_keywords");
	}

	public void setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
	}
	
	public java.lang.String getMetaDescription() {
		return getStr("meta_description");
	}

	public void setIsTop(java.lang.Boolean isTop) {
		set("is_top", isTop);
	}
	
	public java.lang.Boolean getIsTop() {
		return getBoolean("is_top");
	}

	public void setCommission(java.lang.Integer commission) {
		set("commission", commission);
	}
	
	public java.lang.Integer getCommission() {
		return getInt("commission");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("order_list", orderList);
	}
	
	public java.lang.Integer getOrderList() {
		return getInt("order_list");
	}

	public void setLinkTo(java.lang.String linkTo) {
		set("link_to", linkTo);
	}

	public java.lang.String getLinkTo() {
		return getStr("link_to");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
