package io.jpress.module.form.model;

import io.jboot.db.annotation.Table;
import io.jboot.web.json.JsonIgnore;
import io.jpress.module.form.model.base.BaseFormDict;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_dict", primaryKey = "id")
public class FormDict extends BaseFormDict<FormDict> {

    private static final long serialVersionUID = 1L;

    @JsonIgnore
    public boolean isStaticData(){
        Boolean withStatic = getWithStatic();
        return withStatic != null && withStatic;
    }

	
}

