package io.jpress.module.form.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.form.model.base.BaseFormDictItem;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_dict_item", primaryKey = "id")
public class FormDictItem extends BaseFormDictItem<FormDictItem> {

    private static final long serialVersionUID = 1L;

	
}

