package io.jpress.module.form.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.google.common.collect.Sets;
import com.jfinal.kit.Ret;
import com.jfinal.plugin.activerecord.Record;
import io.jboot.db.annotation.Table;
import io.jpress.module.form.model.base.BaseFormInfo;

import javax.servlet.http.HttpServletRequest;
import java.util.*;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_info", primaryKey = "id")
public class FormInfo extends BaseFormInfo<FormInfo> {

    private static final long serialVersionUID = 1L;


    public static final String FORMINFO_STATUS_INIT = "init";
    public static final String FORMINFO_STATUS_PUBLISHED = "published";

    private static final Set<String> fieldTags = Sets.newHashSet("input", "textarea", "select"
            , "range", "radio", "checkbox", "date", "time", "datetime", "switch", "file-upload");


    public List<DbFieldInfo> toDbFieldInfo() {
        String json = getBuilderJson();
        JSONArray datas = JSON.parseArray(json);
        List<DbFieldInfo> dbFieldInfos = new ArrayList<>();

        parseJsonArrayToDbFieldInfos(datas, dbFieldInfos);

        return dbFieldInfos;
    }


    public Ret checkAllFields() {
        List<DbFieldInfo> dbFieldInfos = toDbFieldInfo();

        Set<String> comments = new HashSet<>();
        for (DbFieldInfo dbFieldInfo : dbFieldInfos) {
            if (!dbFieldInfo.isStateOk()) {
                comments.add(dbFieldInfo.getComment());
            }
        }

        if (comments.isEmpty()) {
            return Ret.ok();
        } else {
            return Ret.fail().set("message", toString(comments, ",") + "的字段名不能为空，或者不能为纯数字。");
        }
    }


    public static String toString(Collection<?> collection, String delimiter) {
        StringJoiner sb = new StringJoiner(delimiter);
        if (collection != null) {
            for (Object o : collection) {
                sb.add(String.valueOf(o));
            }
        }
        return sb.toString();
    }


    public String toCreateTableSql() {
        //CREATE TABLE `form_dict_item` (
        //  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
        //  `text` text COMMENT '文本内容',
        //  `value` varchar(64) DEFAULT NULL COMMENT 'key',
        //  PRIMARY KEY (`id`)
        //) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4;


        StringBuilder sqlBuilder = new StringBuilder();
        sqlBuilder.append("CREATE TABLE `").append(getDataTableName()).append("` (");
        sqlBuilder.append("`id` int(11) unsigned NOT NULL AUTO_INCREMENT,");

        List<DbFieldInfo> dbFieldInfos = toDbFieldInfo();
        for (DbFieldInfo dbFieldInfo : dbFieldInfos) {
            sqlBuilder.append(dbFieldInfo.toSql()).append(",");
        }

        sqlBuilder.append("PRIMARY KEY (`id`)");
        sqlBuilder.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

        return sqlBuilder.toString();
    }


    public Record parseRequestToRecord(HttpServletRequest request) {
        List<DbFieldInfo> dbFieldInfos = toDbFieldInfo();

        Record record = new Record();
        for (DbFieldInfo fieldInfo : dbFieldInfos) {
            record.put(fieldInfo.getName(), request.getParameter(fieldInfo.getParaName()));
        }

        return record;
    }


    public String getDataTableName() {
        return "form_data_" + getId() + "_" + getVersion();
    }


    private void parseJsonArrayToDbFieldInfos(JSONArray datas, List<DbFieldInfo> dbFieldInfos) {
        if (datas == null || datas.isEmpty()) {
            return;
        }

        for (int i = 0; i < datas.size(); i++) {
            JSONObject data = datas.getJSONObject(i);

            JSONObject children = data.getJSONObject("children");

            //容器（布局组件）
            if (children != null) {
                for (String s : children.keySet()) {
                    parseJsonArrayToDbFieldInfos(children.getJSONArray(s), dbFieldInfos);
                }
            }

            //非布局组件数据
            else if (fieldTags.contains(data.getString("tag"))) {

                String fieldName = data.getString("field");
                String fieldType = data.getString("field_type");
                Integer fieldLenth = data.getInteger("field_lenth");

                DbFieldInfo dbFieldInfo = new DbFieldInfo();
                dbFieldInfo.setParaName(data.getString("name"));
                dbFieldInfo.setName(fieldName);
                dbFieldInfo.setType(fieldType);
                dbFieldInfo.setTypeLen(fieldLenth);
                dbFieldInfo.setComment(data.getString("label"));

                dbFieldInfos.add(dbFieldInfo);
            }
        }
    }


    public boolean isPublished() {
        return FORMINFO_STATUS_PUBLISHED.equals(getStatus());
    }
}

