package io.jpress.module.form.model;

import io.jboot.db.annotation.Table;
import io.jboot.web.json.JsonIgnore;
import io.jpress.module.form.model.base.BaseFormDatasource;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_datasource", primaryKey = "id")
public class FormDatasource extends BaseFormDatasource<FormDatasource> {

    private static final long serialVersionUID = 1L;


    @JsonIgnore
    public boolean isStaticData(){
        Boolean withStatic = getWithStatic();
        return withStatic != null && withStatic;
    }
	
}

