package io.jpress.module.form.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.form.model.base.BaseFormDatasourceItem;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_datasource_item", primaryKey = "id")
public class FormDatasourceItem extends BaseFormDatasourceItem<FormDatasourceItem> {

    private static final long serialVersionUID = 1L;

	
}

