package io.jpress.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jpress.base.BaseOptionsModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOrderInvoice<M extends BaseUserOrderInvoice<M>> extends BaseOptionsModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 发票类型
     */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 发票类型
     */
	public java.lang.String getType() {
		return getStr("type");
	}

    /**
     * 发票抬头
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 发票抬头
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 发票内容
     */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 发票内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

    /**
     * 纳税人识别号
     */
	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

    /**
     * 纳税人识别号
     */
	public java.lang.String getIdentity() {
		return getStr("identity");
	}

    /**
     * 单位名称
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 单位名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 发票收取人手机号
     */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

    /**
     * 发票收取人手机号
     */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

    /**
     * 发票收取人邮箱
     */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

    /**
     * 发票收取人邮箱
     */
	public java.lang.String getEmail() {
		return getStr("email");
	}

    /**
     * 发票状态
     */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 发票状态
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

    /**
     * json字段扩展
     */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}

    /**
     * json字段扩展
     */
	public java.lang.String getOptions() {
		return getStr("options");
	}

    /**
     * 修改时间
     */
	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

    /**
     * 修改时间
     */
	public java.util.Date getModified() {
		return get("modified");
	}

    /**
     * 创建时间
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreated() {
		return get("created");
	}

}
