package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplateBlockOption<M extends BaseTemplateBlockOption<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 模板ID
     */
	public void setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
	}

    /**
     * 模板ID
     */
	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

    /**
     * 站点 ID
     */
	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

    /**
     * 站点 ID
     */
	public java.lang.Long getSiteId() {
		return getLong("site_id");
	}

    /**
     * 配置内容
     */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}

    /**
     * 配置内容
     */
	public java.lang.String getOptions() {
		return getStr("options");
	}

}

