package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAmountStatement<M extends BaseUserAmountStatement<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setAction(java.lang.String action) {
		set("action", action);
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

	public void setActionName(java.lang.String actionName) {
		set("action_name", actionName);
	}
	
	public java.lang.String getActionName() {
		return getStr("action_name");
	}

	public void setActionDesc(java.lang.String actionDesc) {
		set("action_desc", actionDesc);
	}
	
	public java.lang.String getActionDesc() {
		return getStr("action_desc");
	}

	public void setActionRelationType(java.lang.String actionRelationType) {
		set("action_relation_type", actionRelationType);
	}
	
	public java.lang.String getActionRelationType() {
		return getStr("action_relation_type");
	}

	public void setActionRelationId(java.lang.Long actionRelationId) {
		set("action_relation_id", actionRelationId);
	}
	
	public java.lang.Long getActionRelationId() {
		return getLong("action_relation_id");
	}

	public void setActionOrderId(java.lang.Long actionOrderId) {
		set("action_order_id", actionOrderId);
	}
	
	public java.lang.Long getActionOrderId() {
		return getLong("action_order_id");
	}

	public void setActionPaymentId(java.lang.Long actionPaymentId) {
		set("action_payment_id", actionPaymentId);
	}
	
	public java.lang.Long getActionPaymentId() {
		return getLong("action_payment_id");
	}

	public void setOldAmount(java.math.BigDecimal oldAmount) {
		set("old_amount", oldAmount);
	}
	
	public java.math.BigDecimal getOldAmount() {
		return get("old_amount");
	}

	public void setChangeAmount(java.math.BigDecimal changeAmount) {
		set("change_amount", changeAmount);
	}
	
	public java.math.BigDecimal getChangeAmount() {
		return get("change_amount");
	}

	public void setNewAmount(java.math.BigDecimal newAmount) {
		set("new_amount", newAmount);
	}
	
	public java.math.BigDecimal getNewAmount() {
		return get("new_amount");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}
	
	public java.lang.String getOptions() {
		return getStr("options");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

}
