package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponCode<M extends BaseCouponCode<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 类型ID
     */
	public void setCouponId(java.lang.Long couponId) {
		set("coupon_id", couponId);
	}

    /**
     * 类型ID
     */
	public java.lang.Long getCouponId() {
		return getLong("coupon_id");
	}

    /**
     * 优惠券标题
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 优惠券标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 优惠码
     */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

    /**
     * 优惠码
     */
	public java.lang.String getCode() {
		return getStr("code");
	}

    /**
     * 用户ID
     */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

    /**
     * 用户ID
     */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 状态 1 有人领取、正常使用  2 未有人领取不能使用  3 已经使用，不能被再次使用  9 已经被认为标识不可用
     */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态 1 有人领取、正常使用  2 未有人领取不能使用  3 已经使用，不能被再次使用  9 已经被认为标识不可用
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

    /**
     * 领取时间
     */
	public void setValidTime(java.util.Date validTime) {
		set("valid_time", validTime);
	}

    /**
     * 领取时间
     */
	public java.util.Date getValidTime() {
		return get("valid_time");
	}

    /**
     * 创建时间，创建时可能不会有人领取
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建时间，创建时可能不会有人领取
     */
	public java.util.Date getCreated() {
		return get("created");
	}

}
