package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTagMapping<M extends BaseUserTagMapping<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 用户ID
     */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

    /**
     * 用户ID
     */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 标签ID
     */
	public void setTagId(java.lang.Long tagId) {
		set("tag_id", tagId);
	}

    /**
     * 标签ID
     */
	public java.lang.Long getTagId() {
		return getLong("tag_id");
	}

}

