package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRoleMapping<M extends BaseUserRoleMapping<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 用户ID
     */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

    /**
     * 用户ID
     */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 角色ID
     */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

    /**
     * 角色ID
     */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

}

