package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends JbootModel<M> implements IBean {

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	public void setPermissionId(java.lang.Long permissionId) {
		set("permission_id", permissionId);
	}
	
	public java.lang.Long getPermissionId() {
		return getLong("permission_id");
	}

}
