package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplateBlockOption<M extends BaseTemplateBlockOption<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
	}

	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

    /**
     * 站点
     */
	public void setSite(java.lang.Integer site) {
		set("site", site);
	}

    /**
     * 站点
     */
	public java.lang.Integer getSite() {
		return getInt("site");
	}

    /**
     * 配置内容
     */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}

    /**
     * 配置内容
     */
	public java.lang.String getOptions() {
		return getStr("options");
	}

}

