package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOrder<M extends BaseUserOrder<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNs(java.lang.Integer ns) {
		set("ns", ns);
	}
	
	public java.lang.Integer getNs() {
		return getInt("ns");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
	}
	
	public java.lang.Long getBuyerId() {
		return getLong("buyer_id");
	}

	public void setBuyerNickname(java.lang.String buyerNickname) {
		set("buyer_nickname", buyerNickname);
	}
	
	public java.lang.String getBuyerNickname() {
		return getStr("buyer_nickname");
	}

	public void setTradeStatus(java.lang.Integer tradeStatus) {
		set("trade_status", tradeStatus);
	}
	
	public java.lang.Integer getTradeStatus() {
		return getInt("trade_status");
	}

	public void setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
	}
	
	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}

	public void setDistId(java.lang.Long distId) {
		set("dist_id", distId);
	}
	
	public java.lang.Long getDistId() {
		return getLong("dist_id");
	}

	public void setDistAmount(java.math.BigDecimal distAmount) {
		set("dist_amount", distAmount);
	}
	
	public java.math.BigDecimal getDistAmount() {
		return get("dist_amount");
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
	}
	
	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	public void setCouponNo(java.lang.String couponNo) {
		set("coupon_no", couponNo);
	}
	
	public java.lang.String getCouponNo() {
		return getStr("coupon_no");
	}

	public void setCouponAmount(java.math.BigDecimal couponAmount) {
		set("coupon_amount", couponAmount);
	}
	
	public java.math.BigDecimal getCouponAmount() {
		return get("coupon_amount");
	}

	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("pay_amount", payAmount);
	}
	
	public java.math.BigDecimal getPayAmount() {
		return get("pay_amount");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setPaymentId(java.lang.Long paymentId) {
		set("payment_id", paymentId);
	}
	
	public java.lang.Long getPaymentId() {
		return getLong("payment_id");
	}

	public void setPaymentOuterNo(java.lang.String paymentOuterNo) {
		set("payment_outer_no", paymentOuterNo);
	}
	
	public java.lang.String getPaymentOuterNo() {
		return getStr("payment_outer_no");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
	}
	
	public java.lang.Integer getDeliveryType() {
		return getInt("delivery_type");
	}

	public void setDeliveryCompany(java.lang.String deliveryCompany) {
		set("delivery_company", deliveryCompany);
	}
	
	public java.lang.String getDeliveryCompany() {
		return getStr("delivery_company");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setDeliveryStartTime(java.util.Date deliveryStartTime) {
		set("delivery_start_time", deliveryStartTime);
	}
	
	public java.util.Date getDeliveryStartTime() {
		return get("delivery_start_time");
	}

	public void setDeliveryFinishTime(java.util.Date deliveryFinishTime) {
		set("delivery_finish_time", deliveryFinishTime);
	}
	
	public java.util.Date getDeliveryFinishTime() {
		return get("delivery_finish_time");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}
	
	public java.lang.String getOptions() {
		return getStr("options");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

}
