package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApiApplication<M extends BaseApiApplication<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setAppkey(java.lang.String appkey) {
		set("appkey", appkey);
	}
	
	public java.lang.String getAppkey() {
		return getStr("appkey");
	}

	public void setSecret(java.lang.String secret) {
		set("secret", secret);
	}
	
	public java.lang.String getSecret() {
		return getStr("secret");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
