package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermissionMapping<M extends BaseRolePermissionMapping<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 角色ID
     */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

    /**
     * 角色ID
     */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

    /**
     * 权限ID
     */
	public void setPermissionId(java.lang.Long permissionId) {
		set("permission_id", permissionId);
	}

    /**
     * 权限ID
     */
	public java.lang.Long getPermissionId() {
		return getLong("permission_id");
	}

}

