package io.jpress.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jpress.base.BaseOptionsModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends BaseOptionsModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 姓名
     */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}

    /**
     * 姓名
     */
	public java.lang.String getUsername() {
		return getStr("username");
	}

    /**
     * 手机号
     */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

    /**
     * 手机号
     */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

    /**
     * 省
     */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

    /**
     * 省
     */
	public java.lang.String getProvince() {
		return getStr("province");
	}

    /**
     * 市
     */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

    /**
     * 市
     */
	public java.lang.String getCity() {
		return getStr("city");
	}

    /**
     * 区（县）
     */
	public void setDistrict(java.lang.String district) {
		set("district", district);
	}

    /**
     * 区（县）
     */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

    /**
     * 详细地址到门牌号
     */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

    /**
     * 详细地址到门牌号
     */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

    /**
     * 邮政编码
     */
	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

    /**
     * 邮政编码
     */
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

    /**
     * 是否默认,1是，0否
     */
	public void setWidthDefault(java.lang.Boolean widthDefault) {
		set("width_default", widthDefault);
	}

    /**
     * 是否默认,1是，0否
     */
	public java.lang.Boolean getWidthDefault() {
		return get("width_default");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}

	public java.lang.String getOptions() {
		return getStr("options");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

	public java.util.Date getModified() {
		return get("modified");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
