package io.jpress.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jpress.base.BaseOptionsModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAmountPayout<M extends BaseUserAmountPayout<M>> extends BaseOptionsModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 申请提现用户
     */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

    /**
     * 申请提现用户
     */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 用户的真实名字
     */
	public void setUserRealName(java.lang.String userRealName) {
		set("user_real_name", userRealName);
	}

    /**
     * 用户的真实名字
     */
	public java.lang.String getUserRealName() {
		return getStr("user_real_name");
	}

    /**
     * 用户的身份证号码
     */
	public void setUserIdcard(java.lang.String userIdcard) {
		set("user_idcard", userIdcard);
	}

    /**
     * 用户的身份证号码
     */
	public java.lang.String getUserIdcard() {
		return getStr("user_idcard");
	}

    /**
     * 提现金额
     */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

    /**
     * 提现金额
     */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

    /**
     * 提现类型
     */
	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

    /**
     * 提现类型
     */
	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

    /**
     * 提现账号：可能是微信的openId，可能是支付宝账号，可能是银行账号
     */
	public void setPayTo(java.lang.String payTo) {
		set("pay_to", payTo);
	}

    /**
     * 提现账号：可能是微信的openId，可能是支付宝账号，可能是银行账号
     */
	public java.lang.String getPayTo() {
		return getStr("pay_to");
	}

    /**
     * 提现成功证明，一般是转账截图
     */
	public void setPaySuccessProof(java.lang.String paySuccessProof) {
		set("pay_success_proof", paySuccessProof);
	}

    /**
     * 提现成功证明，一般是转账截图
     */
	public java.lang.String getPaySuccessProof() {
		return getStr("pay_success_proof");
	}

    /**
     * 提现手续费
     */
	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

    /**
     * 提现手续费
     */
	public java.math.BigDecimal getFee() {
		return get("fee");
	}

    /**
     * 申请提现成功后会生成一个扣款记录
     */
	public void setStatementId(java.lang.Long statementId) {
		set("statement_id", statementId);
	}

    /**
     * 申请提现成功后会生成一个扣款记录
     */
	public java.lang.Long getStatementId() {
		return getLong("statement_id");
	}

    /**
     * 状态
     */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

    /**
     * 用户备注
     */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

    /**
     * 用户备注
     */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

    /**
     * 回绝提现时给出原因
     */
	public void setFeedback(java.lang.String feedback) {
		set("feedback", feedback);
	}

    /**
     * 回绝提现时给出原因
     */
	public java.lang.String getFeedback() {
		return getStr("feedback");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}

	public java.lang.String getOptions() {
		return getStr("options");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

	public java.util.Date getModified() {
		return get("modified");
	}

}
