package io.jpress.module.shop.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.shop.model.base.BaseUserOrder;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_order", primaryKey = "id")
public class UserOrder extends BaseUserOrder<UserOrder> {

    private static final long serialVersionUID = 1L;

	
}
