package io.jpress.module.job.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jpress.base.BaseSortOptionsModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobCategory<M extends BaseJobCategory<M>> extends BaseSortOptionsModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 分类的类型：category、address
     */
	public void setType(java.lang.String type) {
		set("type", type);
	}

    /**
     * 分类的类型：category、address
     */
	public java.lang.String getType() {
		return getStr("type");
	}

    /**
     * 父id
     */
	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}

    /**
     * 父id
     */
	public java.lang.Long getPid() {
		return getLong("pid");
	}

    /**
     * 分类名称
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 分类名称
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 摘要
     */
	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

    /**
     * 摘要
     */
	public java.lang.String getSummary() {
		return getStr("summary");
	}

    /**
     * 该分类下的岗位数量
     */
	public void setCount(java.lang.Long count) {
		set("count", count);
	}

    /**
     * 该分类下的岗位数量
     */
	public java.lang.Long getCount() {
		return getLong("count");
	}

    /**
     * 排序编码
     */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

    /**
     * 排序编码
     */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

    /**
     * 标识
     */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

    /**
     * 标识
     */
	public java.lang.String getFlag() {
		return getStr("flag");
	}

    /**
     * 创建日期
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

    /**
     * 修改日期
     */
	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

    /**
     * 修改日期
     */
	public java.util.Date getModified() {
		return getDate("modified");
	}

    /**
     * 站点ID
     */
	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

    /**
     * 站点ID
     */
	public java.lang.Long getSiteId() {
		return getLong("site_id");
	}

}

