FROM maven:3.6-jdk-8-alpine
LABEL maintainer="Michael Yang<fuhai999@gmail.com>"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apk add --update font-adobe-100dpi ttf-dejavu


