package io.jpress.module.product.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.product.model.base.BaseProductComment;

/**
 * Generated by JPress.
 */
@Table(tableName = "product_comment", primaryKey = "id")
public class ProductComment extends BaseProductComment<ProductComment> {

    private static final long serialVersionUID = 1L;

	
}
