package io.jpress.module.page.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSinglePage<M extends BaseSinglePage<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键ID
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 分类ID
     */
	public void setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
	}

    /**
     * 分类ID
     */
	public java.lang.Long getCategoryId() {
		return getLong("category_id");
	}

    /**
     * slug
     */
	public void setSlug(java.lang.String slug) {
		set("slug", slug);
	}

    /**
     * slug
     */
	public java.lang.String getSlug() {
		return getStr("slug");
	}

    /**
     * 标题
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 内容
     */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

    /**
     * 编辑模式：html可视化，markdown ..
     */
	public void setEditMode(java.lang.String editMode) {
		set("edit_mode", editMode);
	}

    /**
     * 编辑模式：html可视化，markdown ..
     */
	public java.lang.String getEditMode() {
		return getStr("edit_mode");
	}

    /**
     * 链接
     */
	public void setLinkTo(java.lang.String linkTo) {
		set("link_to", linkTo);
	}

    /**
     * 链接
     */
	public java.lang.String getLinkTo() {
		return getStr("link_to");
	}

    /**
     * 摘要
     */
	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

    /**
     * 摘要
     */
	public java.lang.String getSummary() {
		return getStr("summary");
	}

    /**
     * 缩略图
     */
	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

    /**
     * 缩略图
     */
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

    /**
     * 装饰图
     */
	public void setOrnament(java.lang.String ornament) {
		set("ornament", ornament);
	}

    /**
     * 装饰图
     */
	public java.lang.String getOrnament() {
		return getStr("ornament");
	}

    /**
     * 样式
     */
	public void setStyle(java.lang.String style) {
		set("style", style);
	}

    /**
     * 样式
     */
	public java.lang.String getStyle() {
		return getStr("style");
	}

    /**
     * 标识
     */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

    /**
     * 标识
     */
	public java.lang.String getFlag() {
		return getStr("flag");
	}

    /**
     * 状态
     */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

    /**
     * 评论状态，默认允许评论
     */
	public void setCommentStatus(java.lang.Boolean commentStatus) {
		set("comment_status", commentStatus);
	}

    /**
     * 评论状态，默认允许评论
     */
	public java.lang.Boolean getCommentStatus() {
		return getBoolean("comment_status");
	}

    /**
     * 评论总数
     */
	public void setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
	}

    /**
     * 评论总数
     */
	public java.lang.Long getCommentCount() {
		return getLong("comment_count");
	}

    /**
     * 最后评论时间
     */
	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}

    /**
     * 最后评论时间
     */
	public java.util.Date getCommentTime() {
		return getDate("comment_time");
	}

    /**
     * 访问量
     */
	public void setViewCount(java.lang.Long viewCount) {
		set("view_count", viewCount);
	}

    /**
     * 访问量
     */
	public java.lang.Long getViewCount() {
		return getLong("view_count");
	}

    /**
     * 创建日期
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

    /**
     * 最后更新日期
     */
	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

    /**
     * 最后更新日期
     */
	public java.util.Date getModified() {
		return getDate("modified");
	}

	/**
	 * SEO标题
	 */
	public void setMetaTitle(java.lang.String metaTitle) {
		set("meta_title", metaTitle);
	}

	/**
	 * SEO标题
	 */
	public java.lang.String getMetaTitle() {
		return getStr("meta_title");
	}

    /**
     * SEO关键字
     */
	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

    /**
     * SEO关键字
     */
	public java.lang.String getMetaKeywords() {
		return getStr("meta_keywords");
	}

    /**
     * SEO描述信息
     */
	public void setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
	}

    /**
     * SEO描述信息
     */
	public java.lang.String getMetaDescription() {
		return getStr("meta_description");
	}

    /**
     * 备注信息
     */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

    /**
     * 备注信息
     */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

    /**
     * 站点ID
     */
	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

    /**
     * 站点ID
     */
	public java.lang.Long getSiteId() {
		return getLong("site_id");
	}

}

