package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseApiApplication;

/**
 * Generated by Jboot.
 */
@Table(tableName = "api_application", primaryKey = "id")
public class ApiApplication extends BaseApiApplication<ApiApplication> {
	
}
