package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseAttachmentVideo;

/**
 * Generated by JPress.
 */
@Table(tableName = "attachment_video", primaryKey = "id")
public class AttachmentVideo extends BaseAttachmentVideo<AttachmentVideo> {

    private static final long serialVersionUID = 1L;

	
}

