package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseAttachmentCategory;

/**
 * Generated by JPress.
 */
@Table(tableName = "attachment_category", primaryKey = "id")
public class AttachmentCategory extends BaseAttachmentCategory<AttachmentCategory> {

    private static final long serialVersionUID = 1L;

	
}

