package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseCouponUsedRecord;

/**
 * Generated by JPress.
 */
@Table(tableName = "coupon_used_record", primaryKey = "id")
public class CouponUsedRecord extends BaseCouponUsedRecord<CouponUsedRecord> {

    private static final long serialVersionUID = 1L;

	
}
