package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseCouponCode;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by JPress.
 */
@Table(tableName = "coupon_code", primaryKey = "id")
public class CouponCode extends BaseCouponCode<CouponCode> {

    private static final long serialVersionUID = 1L;

    public static final int STATUS_NORMAL = 1;
    public static final int STATUS_INVALID = 9;


    public boolean isNormal() {
        Integer status = getStatus();
        return status != null && status == STATUS_NORMAL;
    }


    public static final Map<Integer, String> statusTexts = new HashMap<>();

    static {
        statusTexts.put(STATUS_NORMAL, "正常");
        statusTexts.put(STATUS_INVALID, "失效");
    }


}
