package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseCoupon;

/**
 * Generated by JPress.
 */
@Table(tableName = "coupon", primaryKey = "id")
public class Coupon extends BaseCoupon<Coupon> {

    private static final long serialVersionUID = 1L;

	
}
