package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseInterfaceApp;

/**
 * Generated by Jboot.
 */
@Table(tableName = "interface_app", primaryKey = "id")
public class InterfaceApp extends BaseInterfaceApp<InterfaceApp> {
	
}
