package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMemberDistAmount;

/**
 * Generated by JPress.
 */
@Table(tableName = "member_dist_amount", primaryKey = "id")
public class MemberDistAmount extends BaseMemberDistAmount<MemberDistAmount> {

    private static final long serialVersionUID = 1L;

	
}
