package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMember;

/**
 * Generated by JPress.
 */
@Table(tableName = "member", primaryKey = "id")
public class Member extends BaseMember<Member> {

    private static final long serialVersionUID = 1L;

    public static final String SOURCE_BUY = "buy";

    public static final int STATUS_NORMAL = 9;

    public boolean isNormal() {
        Integer status = getStatus();
        return status != null && status == STATUS_NORMAL;
    }


}
