package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMemberJoinedRecord;

/**
 * Generated by JPress.
 */
@Table(tableName = "member_joined_record", primaryKey = "id")
public class MemberJoinedRecord extends BaseMemberJoinedRecord<MemberJoinedRecord> {

    private static final long serialVersionUID = 1L;

    public static final String JOIN_TYPE_BUY = Member.SOURCE_BUY; //用户购买
    public static final String JOIN_TYPE_FREE = Member.SOURCE_FREE; //免费赠送
    public static final String JOIN_TYPE_OTHER = Member.SOURCE_OTHER; //其他

	
}
