package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMember;

/**
 * Generated by JPress.
 */
@Table(tableName = "member", primaryKey = "id")
public class Member extends BaseMember<Member> {

    private static final long serialVersionUID = 1L;

	
}
