package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMemberPrice;

/**
 * Generated by JPress.
 */
@Table(tableName = "member_price", primaryKey = "id")
public class MemberPrice extends BaseMemberPrice<MemberPrice> {

    private static final long serialVersionUID = 1L;

	
}
