package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMemberUser;

/**
 * Generated by JPress.
 */
@Table(tableName = "member_user", primaryKey = "id")
public class MemberUser extends BaseMemberUser<MemberUser> {

    private static final long serialVersionUID = 1L;

	
}
