package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseMenu;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "menu", primaryKey = "id")
public class Menu extends BaseMenu<Menu> {


    /**
     * header：前台顶部菜单；
     * main:前台主菜单；
     * footer:前台底部菜单；
     */
    public static final String TYPE_HEADER = "header"; //前台的头部菜单
    public static final String TYPE_MAIN = "main"; //前台的主菜单，一般用在左边导航或者右边导航，根据模板本身来决定的
    public static final String TYPE_FOOTER = "footer"; //前台的底部菜单


    /**
     * 是否是顶级菜单
     *
     * @return
     */
    public boolean isTopMenu() {
        return getPid() != null && getPid() == 0;
    }

    private List<Menu> childs;

    public List<Menu> getChilds() {
        return childs;
    }

    public void setChilds(List<Menu> childs) {
        this.childs = childs;
    }

    public void addChild(Menu child) {
        if (childs == null) {
            childs = new ArrayList<>();
        }
        childs.add(child);
    }

    private int layerNO = 0;

    public int getLayerNO() {
        return layerNO;
    }

    public void setLayerNO(int layerNO) {
        this.layerNO = layerNO;
    }

    public String getLayerString() {
        if (layerNO == 0) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < layerNO; i++) {
            if (i == 0)
                sb.append("|—");
            else
                sb.append("—");
        }
        return sb.toString();
    }

    public boolean isMyChild(long id) {
        if (childs == null || childs.isEmpty()) {
            return false;
        }

        return isMyChild(childs, id);
    }

    private boolean isMyChild(List<Menu> menus, long id) {
        for (Menu menu : menus) {
            if (menu.getId() == id) {
                return true;
            }

            if (menu.getChilds() != null) {
                boolean isChild = isMyChild(menu.getChilds(), id);
                if (isChild) return true;
            }
        }

        return false;
    }

}
