/**
 * Copyright (c) 2016-2019, Michael Yang 杨福海 (fuhai999@gmail.com).
 * <p>
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BasePaymentRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "payment_record", primaryKey = "id")
public class PaymentRecord extends BasePaymentRecord<PaymentRecord> {
    private static final long serialVersionUID = 1L;

    /**
     * 业务类型
     */
    public static final String TRX_TYPE_RECHARGE = "recharge"; //用户充值
    public static final String TRX_TYPE_ORDER = "order"; //订单支付


    /**
     * 支付状态
     */
    public static final int PAY_STATUS_PREPAY = 1; //生成订单
    public static final int PAY_STATUS_SUCCESS = 9; //支付成功
    public static final int PAY_STATUS_FAILURE = 99; //支付失败


    /**
     * 是否支付成功
     *
     * @return
     */
    public boolean isPaySuccess() {
        return getPayStatus() != null && PAY_STATUS_SUCCESS == getPayStatus();
    }


    /**
     * 是否处于预支付状态
     *
     * @return
     */
    public boolean isPayPre() {
        return getPayStatus() != null && PAY_STATUS_PREPAY == getPayStatus();
    }

}
