/**
 * Copyright (c) 2016-2019, Michael Yang 杨福海 (fuhai999@gmail.com).
 * <p>
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BasePaymentRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "payment_record", primaryKey = "id")
public class PaymentRecord extends BasePaymentRecord<PaymentRecord> {
    private static final long serialVersionUID = 1L;

    /**
     * 业务类型
     */
    public static final String TRX_TYPE_RECHARGE = "recharge"; //用户充值
    public static final String TRX_TYPE_ORDER = "order"; //订单支付
    public static final String TRX_TYPE_MEMBER = "member"; //购买会员


    /**
     * 支付状态
     */
    public static final int PAY_STATUS_PREPAY = 1; //生成订单
    public static final int PAY_STATUS_FAILURE = 2; //支付失败
    public static final int PAY_STATUS_SUCCESS_AUTO = 9; //自动在线支付成功
    public static final int PAY_STATUS_SUCCESS_ALIPAY = 10; //支付宝转账支付成功
    public static final int PAY_STATUS_SUCCESS_WECHAT = 11; //微信转账支付成功
    public static final int PAY_STATUS_SUCCESS_OFFLINE = 12; //线下支付支付成功（一般是银行转账等）
    public static final int PAY_STATUS_SUCCESS_OTHER = 13; //其他支付方式支付成功


    /**
     * 支付类型
     */
    public static final String PAY_TYPE_AMOUNT = "amount"; //越支付
    public static final String PAY_TYPE_WECHAT = "wechat"; //微信在线支付
    public static final String PAY_TYPE_WECHATX = "wechatx"; //微信好友转账支付（包括红包等）
    public static final String PAY_TYPE_ALIPAY = "alipay"; //支付宝在线支付
    public static final String PAY_TYPE_ALIPAYX = "alipayx"; //支付宝转账
    public static final String PAY_TYPE_PAYPAL = "paypal"; //paypal在线支付
    public static final String PAY_TYPE_OFFLINE = "offline"; //线下支付
    public static final String PAY_TYPE_OTHER = "other"; //其他支付


    /**
     * payment 状态
     */
    public static final int STATUS_PAY_PRE = 1; //预支付
    public static final int STATUS_PAY_FAILURE = 2; //支付失败
    public static final int STATUS_PAY_SUCCESS = 9; //支付成功
    public static final int STATUS_REFUND_PRE = 11; //预退款
    public static final int STATUS_REFUNDING = 12; //退款中
    public static final int STATUS_REFUND_FAILURE = 13; //退款失败
    public static final int STATUS_REFUND_SUCCESS = 19; //退款成功

    /**
     * 是否可以对支付记录进行手动入账
     *
     * @return
     */
    public boolean isCanUpdateByUser() {
        Integer payStatus = getPayStatus();
        String payType = getPayType();

        return payStatus != null
                && payStatus == PAY_STATUS_PREPAY
                && (PAY_TYPE_WECHATX.equals(payType) || PAY_TYPE_ALIPAYX.equals(payType));
    }


    /**
     * 是否支付成功
     *
     * @return
     */
    public boolean isPaySuccess() {
        return getPayStatus() != null && getPayStatus() > PAY_STATUS_SUCCESS_AUTO;
    }


    /**
     * 是否处于预支付状态
     *
     * @return
     */
    public boolean isPayPre() {
        return getPayStatus() != null && PAY_STATUS_PREPAY == getPayStatus();
    }

}
