package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BasePaymentRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "payment_record", primaryKey = "id")
public class PaymentRecord extends BasePaymentRecord<PaymentRecord> {
	
}
