package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BasePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "permission", primaryKey = "id")
public class Permission extends BasePermission<Permission> {
	
}
