package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jboot.utils.StringUtils;
import io.jpress.model.base.BasePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "permission", primaryKey = "id")
public class Permission extends BasePermission<Permission> {

    public static final int TYPE_ACTION = 1;
    public static final int TYPE_MENU = 2;
    public static final int TYPE_DIV = 3;
    public static final int TYPE_CUSTOM = 4;


    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Permission)) {
            return false;
        }

        Permission p = (Permission) o;

        return getActionKey().equals(p.getActionKey());
    }

    public String getShortNode() {
        String node = getNode();
        if (StringUtils.isBlank(node)) {
            return node;
        }

        if (!node.contains(".")) {
            return node;
        }

        String[] strings = node.split("\\.");
        return "..." + strings[strings.length - 1];
    }

    public String getTypeText() {
        switch (getType()) {
            case TYPE_ACTION:
                return "功能";
            case TYPE_CUSTOM:
                return "自定义";
            case TYPE_MENU:
                return "菜单";
            case TYPE_DIV:
                return "页面块";
        }
        return "未知类型";
    }

    public boolean isActionPermission() {
        return getType() != null && TYPE_ACTION == getType();
    }


    public boolean isDivPermission() {
        return getType() != null && TYPE_DIV == getType();
    }


    public boolean isMenuPermission() {
        return getType() != null && TYPE_MENU == getType();
    }


    public boolean isCustomPermission() {
        return getType() != null && TYPE_CUSTOM == getType();
    }
}
