package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "role", primaryKey = "id")
public class Role extends BaseRole<Role> {

    public static final String ADMIN_FLAG = "jpsa";

    /**
     * 是否是超级管理员的权限
     *
     * @return true : 是超级管理员，否则不是
     */
    public boolean isSuperAdmin() {
        return ADMIN_FLAG.equals(getFlag());
    }

}
