package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseRolePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "role_permission", primaryKey = "permission_id,role_id")
public class RolePermission extends BaseRolePermission<RolePermission> {
	
}
