package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jboot.utils.StrUtil;
import io.jpress.model.base.BaseSiteInfo;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JPress.
 */
@Table(tableName = "site_info", primaryKey = "id")
public class SiteInfo extends BaseSiteInfo<SiteInfo> {

    private static final long serialVersionUID = 1L;
    private Set<Long> roleArray;
    private Set<String> langArray;


    public boolean hasRole(Long roleId) {
        for (Long role : getBindRolesAsSet()) {
            if (roleId.equals(role)) {
                return true;
            }
        }
        return false;
    }


    public boolean hasLang(String lang) {
        for (String s : getBindLangsAsSet()) {
            if (s.equalsIgnoreCase(lang)) {
                return true;
            }
        }
        return false;
    }


    public Set<String > getBindLangsAsSet() {
        if (langArray == null) {
            langArray = toStringSet(getBindLangs());
        }
        return langArray;
    }


    public Set<Long> getBindRolesAsSet() {
        if (roleArray == null) {
            roleArray = toLongSet(getBindRoles());
        }
        return roleArray;
    }


    private Set<Long> toLongSet(String string) {
        Set<Long> set = new HashSet<>();
        if (StrUtil.isNotBlank(string)) {
            String[] strings = string.split(",");
            for (String s : strings) {
                set.add(Long.parseLong(s));
            }
        }
        return set;
    }


    private Set<String> toStringSet(String string) {
        Set<String> set = new HashSet<>();
        if (StrUtil.isNotBlank(string)) {
            String[] strings = string.split(",");
            for (String s : strings) {
                set.add(s.trim());
            }
        }
        return set;
    }


}

