package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseTemplateBlockOption;

/**
 * Generated by JPress.
 */
@Table(tableName = "template_block_option", primaryKey = "id")
public class TemplateBlockOption extends BaseTemplateBlockOption<TemplateBlockOption> {

    private static final long serialVersionUID = 1L;

	
}

