package io.jpress.model;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import io.jboot.db.annotation.Table;
import io.jboot.utils.StrUtil;
import io.jpress.model.base.BaseTemplateBlockOption;

/**
 * Generated by JPress.
 */
@Table(tableName = "template_block_option", primaryKey = "template_id,site_id")
public class TemplateBlockOption extends BaseTemplateBlockOption<TemplateBlockOption> {

    private static final long serialVersionUID = 1L;


    /**
     * 根据 block 容器 id 获取其数据
     * @param containerId
     * @return
     */
    public JSONArray getJsonArrayByContainerId(String containerId){
        String options = getOptions();
        if (StrUtil.isBlank(options)){
            return null;
        }
        JSONArray containers = JSONArray.parseArray(options);
        for (int i = 0; i < containers.size(); i++) {
            JSONObject container = containers.getJSONObject(i);
            if (containerId.equals(container.getString("id"))){
                JSONObject children = container.getJSONObject("children");
               return children != null ? children.getJSONArray("0") : null;
            }
        }

        return null;
    }

	
}

