package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserFavorite;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_favorite", primaryKey = "id")
public class UserFavorite extends BaseUserFavorite<UserFavorite> {

    private static final long serialVersionUID = 1L;

	
}
