package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserAmountStatement;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_amount_statement", primaryKey = "id")
public class UserAmountStatement extends BaseUserAmountStatement<UserAmountStatement> {

    private static final long serialVersionUID = 1L;


}
