package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserFavorite;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_favorite", primaryKey = "id")
public class UserFavorite extends BaseUserFavorite<UserFavorite> {
    public static final String FAV_TYPE_PRODUCT = "product";
    public static final String FAV_TYPE_ARTICLE = "article";
    public static final String FAV_TYPE_ARTICLE_TEXT = "文章";
    public static final String FAV_TYPE_PRODUCT_TEXT = "商品";
    private static final long serialVersionUID = 1L;


}
