package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserOrderDelivery;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_order_delivery", primaryKey = "id")
public class UserOrderDelivery extends BaseUserOrderDelivery<UserOrderDelivery> {

    private static final long serialVersionUID = 1L;

    public static final int STATUS_DELIVERING = 1;
    public static final int STATUS_FINISHED = 9;

	
}
