package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jboot.utils.StrUtil;
import io.jpress.model.base.BaseUserOrderItem;
import org.apache.commons.lang.time.DateUtils;

import java.util.Date;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_order_item", primaryKey = "id")
public class UserOrderItem extends BaseUserOrderItem<UserOrderItem> {

    private static final long serialVersionUID = 1L;

    public boolean canView(){
        if (StrUtil.isBlank(getViewPath()) || StrUtil.isBlank(getViewText())){
            return false;
        }

        if (getViewEffectiveTime() == 0){
            return true;
        }

        return DateUtils.addSeconds(getCreated(),getViewEffectiveTime().intValue()).getTime() > new Date().getTime();
    }

}
