package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserOrder;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_order", primaryKey = "id")
public class UserOrder extends BaseUserOrder<UserOrder> {

    private static final long serialVersionUID = 1L;

    /**
     * 交易状态
     */
    public static final int TRADE_STATUS_TRADING = 1; //交易中
    public static final int TRADE_STATUS_COMPLETED = 2; //交易完成（但是可以申请退款）
    public static final int TRADE_STATUS_CANCEL = 3; //取消交易
    public static final int TRADE_STATUS_APPLY_FOR_REFUNDING = 4; //申请退款
    public static final int TRADE_STATUS_REFUSAL_REFUNDING = 5; //拒绝退款
    public static final int TRADE_STATUS_REFUNDING = 6; //退款中
    public static final int TRADE_STATUS_REFUNDED = 7;//退款完成
    public static final int TRADE_STATUS_FINISHED = 9;//交易结束


    /**
     * 支付状态
     */
    public static final int PAY_STATUS_UNPAY = 1; //未支付
    public static final int PAY_STATUS_PAID_ONLINE = 2;//线上支付完成，线上支付肯定会有 payment 记录
    public static final int PAY_STATUS_PAID_OFFLINE_BY_USERFLAG = 2; //用户主动标识线下支付完成
    public static final int PAY_STATUS_PAID_OFFLINE = 2;//线下直接完成（一般是银行打款）
    public static final int PAY_STATUS_PAID_IM_BY_USERFLAG = 2; //用户主动标识，通过通讯工具付款完成
    public static final int PAY_STATUS_PAID_IM = 2;//im工具付款完成


    public static final Map<Integer, String> tradeStatusTexts = new HashMap<>();
    static {
        tradeStatusTexts.put(TRADE_STATUS_TRADING,"交易中");
        tradeStatusTexts.put(TRADE_STATUS_COMPLETED,"交易完成");
        tradeStatusTexts.put(TRADE_STATUS_CANCEL,"交易结束");
        tradeStatusTexts.put(TRADE_STATUS_APPLY_FOR_REFUNDING,"申请退款中");
        tradeStatusTexts.put(TRADE_STATUS_REFUSAL_REFUNDING,"解决退款");
        tradeStatusTexts.put(TRADE_STATUS_REFUNDING,"退款中");
        tradeStatusTexts.put(TRADE_STATUS_REFUNDED,"退款完成");
        tradeStatusTexts.put(TRADE_STATUS_FINISHED,"交易结束");
    }


    public static final Map<Integer, String> payStatusTexts = new HashMap<>();
    static {
        payStatusTexts.put(PAY_STATUS_UNPAY,"未支付");
        payStatusTexts.put(PAY_STATUS_PAID_ONLINE,"在线支持完成");
        payStatusTexts.put(PAY_STATUS_PAID_OFFLINE_BY_USERFLAG,"线下支付中");
        payStatusTexts.put(PAY_STATUS_PAID_OFFLINE,"线下支付完成");
        payStatusTexts.put(PAY_STATUS_PAID_IM_BY_USERFLAG,"通信工具支付中");
        payStatusTexts.put(PAY_STATUS_PAID_IM,"通信工具支付完成");
    }


    public String getTradeStatusStr() {
        return tradeStatusTexts.get(getTradeStatus());
    }

    public String getPayStatusStr() {
        return payStatusTexts.get(getPayStatus());
    }
}
