package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserCart;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_cart", primaryKey = "id")
public class UserCart extends BaseUserCart<UserCart> {

    private static final long serialVersionUID = 1L;


}
