package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUserOrderItem;

/**
 * Generated by JPress.
 */
@Table(tableName = "user_order_item", primaryKey = "id")
public class UserOrderItem extends BaseUserOrderItem<UserOrderItem> {

    private static final long serialVersionUID = 1L;

}
