package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUtm;

/**
 * Generated by Jboot.
 */
@Table(tableName = "utm", primaryKey = "id")
public class Utm extends BaseUtm<Utm> {
	
}
