package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseUtm;

import java.util.Date;

/**
 * Generated by Jboot.
 */
@Table(tableName = "utm", primaryKey = "id")
public class Utm extends BaseUtm<Utm> {

    public Utm() {
        String[] attrNames = _getAttrNames();
        for (String attr : attrNames) {
            set(attr, null);
        }
        setCreated(new Date());
    }
}
