package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseWechatReplay;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wechat_replay", primaryKey = "id")
public class WechatReplay extends BaseWechatReplay<WechatReplay> {
	
}
