package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseWechatMenu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wechat_menu", primaryKey = "id")
public class WechatMenu extends BaseWechatMenu<WechatMenu> {
	
}
