package io.jpress.module.job.model;

import com.google.common.collect.Sets;
import com.jfinal.upload.UploadFile;
import io.jboot.db.annotation.Table;
import io.jboot.utils.FileUtil;
import io.jpress.module.job.model.base.BaseJobApply;

import javax.validation.constraints.NotNull;
import java.util.Set;

/**
 * Generated by JPress.
 */
@Table(tableName = "job_apply", primaryKey = "id")
public class JobApply extends BaseJobApply<JobApply> {

    private static final long serialVersionUID = 1L;

    public static final String MOBILE_ENABLE = "job_mobile_enable";
    public static final String EMAIL_ENABLE = "job_email_enable";
    public static final String JOB_APPLY_ENABLE = "job_apply_enable";


    public static final String FILE_RESUME = "file-resume";
    public static final String FILE_ATTACHMENT = "file-attachment";

    private static final Set<String> allowSuffixes = Sets.newHashSet(".jpg"
            , ".jpeg", ".png", ".gif", ".webp", ".svg", ".doc", ".docx", ".wps", ".pdf");

    private static final Set<String> allowAttchmentSuffixes = Sets.newHashSet(".zip"
            , ".rar");


    //判断 简历文件类型
    public static boolean isResumeFile(@NotNull UploadFile uploadFile) {
        String suffix = FileUtil.getSuffix(uploadFile.getFile().getName());
        return suffix != null && allowSuffixes.contains(suffix.toLowerCase().trim());
    }


    //判断 简历文件类型  ATTACHMENT
    public static boolean isAttachmentFile(@NotNull UploadFile uploadFile) {
        String suffix = FileUtil.getSuffix(uploadFile.getFile().getName());
        return suffix != null && allowAttchmentSuffixes.contains(suffix.toLowerCase().trim());
    }


}

