package io.jpress.module.job.model;

import com.jfinal.upload.UploadFile;
import io.jboot.db.annotation.Table;
import io.jpress.module.job.model.base.BaseJobApply;

import javax.validation.constraints.NotNull;

/**
 * Generated by JPress.
 */
@Table(tableName = "job_apply", primaryKey = "id")
public class JobApply extends BaseJobApply<JobApply> {

    private static final long serialVersionUID = 1L;

    public static final String MOBILE_ENABLE = "job_mobile_enable";
    public static final String EMAIL_ENABLE = "job_email_enable";
    public static final String JOB_APPLY_ENABLE = "job_apply_enable";


    public static final String FILE_RESUME = "file-resume";
    public static final String FILE_ATTACHMENT = "file-attachment";


    //判断 简历文件类型
    public static boolean fileResumeType(@NotNull UploadFile uploadFile) {

        String fileType = uploadFile.getContentType();

        if (fileType.equals("image/jpeg") ||
                fileType.equals("image/png") ||
                fileType.equals("image/gif") ||
                fileType.equals("image/svg") ||
                fileType.equals("image/jpg") ||
                fileType.equals("image/bmp") ||
                fileType.equals("image/webp") ||
                fileType.equals("application/vnd.openxmlformats-officedocument.wordprocessingml.document") ||
                fileType.equals("application/msword") ||
                fileType.equals("application/kswps") ||
                fileType.equals("application/pdf")) {
            return true;
        } else {
            return false;
        }

    }


    //判断 简历文件类型  ATTACHMENT
    public static boolean fileAttachmentType(@NotNull UploadFile uploadFile) {

        String fileType = uploadFile.getContentType();

        if (fileType.equals("application/x-zip-compressed") ||
                fileType.equals("application/octet-stream")) {
            return true;
        } else {
            return false;
        }

    }


}

