package io.jpress.module.job.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.job.model.base.BaseJobCategory;

/**
 * Generated by JPress.
 */
@Table(tableName = "job_category", primaryKey = "id")
public class JobCategory extends BaseJobCategory<JobCategory> {

    private static final long serialVersionUID = 1L;



    //对应  对字段 count 的增加获取减少
    public static final String ADD = "add";
    public static final String reduce = "reduce";

	
}

