package io.jpress.module.job.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.job.model.base.BaseJobCategory;

/**
 * Generated by JPress.
 */
@Table(tableName = "job_category", primaryKey = "id")
public class JobCategory extends BaseJobCategory<JobCategory> {

    private static final long serialVersionUID = 1L;


    public static final String CATEGORY_TYPE_CATEGORY = "category";


    public static final String CATEGORY_TYPE_ADDRESS = "address";


    @Override
    public JobCategory getParent() {
        return super.getParent();
    }

    @Override
    public boolean isMyChild(long id) {
        return super.isMyChild(id);
    }

    @Override
    public String getLayerString() {
        return super.getLayerString();
    }
}

