package io.jpress.module.page.model;

import io.jboot.db.annotation.Table;
import io.jboot.utils.StrUtil;
import io.jboot.web.json.JsonIgnore;
import io.jpress.module.page.model.base.BaseSinglePageCategory;

/**
 * Generated by JPress.
 */
@Table(tableName = "single_page_category", primaryKey = "id")
public class SinglePageCategory extends BaseSinglePageCategory<SinglePageCategory> {

    private static final long serialVersionUID = 1L;


    @JsonIgnore
    public String getPageView() {
        return StrUtil.isBlank(getStyle()) ? "page.html" : "page_" + getStyle().trim() + ".html";
    }
	
}

