package io.jpress.module.form.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormInfo<M extends BaseFormInfo<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 表单名称
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 表单名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 表单标识
     */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

    /**
     * 表单标识
     */
	public java.lang.String getFlag() {
		return getStr("flag");
	}

    /**
     * 缩略图
     */
	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

    /**
     * 缩略图
     */
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

    /**
     * 表单背景图
     */
	public void setBgImage(java.lang.String bgImage) {
		set("bg_image", bgImage);
	}

    /**
     * 表单背景图
     */
	public java.lang.String getBgImage() {
		return getStr("bg_image");
	}

    /**
     * 表单头图
     */
	public void setHeaderImage(java.lang.String headerImage) {
		set("header_image", headerImage);
	}

    /**
     * 表单头图
     */
	public java.lang.String getHeaderImage() {
		return getStr("header_image");
	}

    /**
     * 是否有钩子
     */
	public void setWithHook(java.lang.Boolean withHook) {
		set("with_hook", withHook);
	}

    /**
     * 是否有钩子
     */
	public java.lang.Boolean getWithHook() {
		return get("with_hook");
	}

    /**
     * 钩子链接
     */
	public void setHookUrl(java.lang.String hookUrl) {
		set("hook_url", hookUrl);
	}

    /**
     * 钩子链接
     */
	public java.lang.String getHookUrl() {
		return getStr("hook_url");
	}

    /**
     * 是否需要审核
     */
	public void setWithAudit(java.lang.Boolean withAudit) {
		set("with_audit", withAudit);
	}

    /**
     * 是否需要审核
     */
	public java.lang.Boolean getWithAudit() {
		return get("with_audit");
	}

    /**
     * 是否需要回复
     */
	public void setWithReply(java.lang.Boolean withReply) {
		set("with_reply", withReply);
	}

    /**
     * 是否需要回复
     */
	public java.lang.Boolean getWithReply() {
		return get("with_reply");
	}

    /**
     * 是否需要输入验证码
     */
	public void setWithValid(java.lang.Boolean withValid) {
		set("with_valid", withValid);
	}

    /**
     * 是否需要输入验证码
     */
	public java.lang.Boolean getWithValid() {
		return get("with_valid");
	}

    /**
     * 是否需要对手机号进行验证
     */
	public void setWithValidMobile(java.lang.Boolean withValidMobile) {
		set("with_valid_mobile", withValidMobile);
	}

    /**
     * 是否需要对手机号进行验证
     */
	public java.lang.Boolean getWithValidMobile() {
		return get("with_valid_mobile");
	}

    /**
     * 表单构建 JSON
     */
	public void setBuilderJson(java.lang.String builderJson) {
		set("builder_json", builderJson);
	}

    /**
     * 表单构建 JSON
     */
	public java.lang.String getBuilderJson() {
		return getStr("builder_json");
	}

    /**
     * 站点ID
     */
	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

    /**
     * 站点ID
     */
	public java.lang.Long getSiteId() {
		return getLong("site_id");
	}

    /**
     * 状态
     */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}

