package io.jpress.core.generator;

import com.jfinal.plugin.activerecord.generator.BaseModelGenerator;
import com.jfinal.plugin.activerecord.generator.TableMeta;

public class JBaseModelGenerator extends BaseModelGenerator {

	public JBaseModelGenerator(String baseModelPackageName,
			String baseModelOutputDir) {
		super(baseModelPackageName, baseModelOutputDir);

		this.classDefineTemplate = "/**%n"
				+ " *  Auto generated by JPress, do not modify this file.%n"
				+ " */%n"
				+ "@SuppressWarnings(\"serial\")%n"
				+ "public abstract class %s<M extends %s<M>> extends JModel<M> implements IBean {%n%n"
				+ "\tpublic static final String CACHE_NAME = \"%s\";%n"
				+ "\tpublic static final String METADATA_TYPE = \"%s\";%n%n"
				
				+ "\tpublic void removeCache(String key){%n"
				+ "\t\tCacheKit.remove(CACHE_NAME, key);%n"
				+ "\t}%n%n"
				
				
				+ "\tpublic void putCache(Object key,Object value){%n"
				+ "\t\tCacheKit.put(CACHE_NAME, key, value);%n"
				+ "\t}%n%n"
				
				
				+ "\tpublic M getCache(Object key){%n"
				+ "\t\treturn CacheKit.get(CACHE_NAME, key);%n"
				+ "\t}%n%n"
				
				
				+ "\tpublic Metadata findMetadata(String key){%n"
				+ "\t\treturn Metadata.findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);%n"
				+ "\t}%n%n"
				

				+ "\tpublic List<Metadata> findMetadataList(){%n"
				+ "\t\treturn Metadata.findListByTypeAndId(METADATA_TYPE, getId());%n"
				+ "\t}%n%n"
				
				
				
				+ "\tpublic M findFirstFromMetadata(String key,Object value){%n"
				+ "\t\tMetadata md = Metadata.findFirstByTypeAndValue(METADATA_TYPE, key, value);%n"
				+ "\t\tif(md != null){%n"
				+ "\t\t\tlong id = md.getObjectId();%n"
				+ "\t\t\treturn findById(id);%n"
				+ "\t\t}%n"
				+ "\t\treturn null;%n"
				+ "\t}%n%n"
				
		
				+ "\tpublic Metadata createMetadata(){%n"
				+ "\t\tMetadata md = new Metadata();%n"
				+ "\t\tmd.setObjectId(getId());%n"
				+ "\t\tmd.setObjectType(METADATA_TYPE);%n"
				+ "\t\treturn md;%n"
				+ "\t}%n%n"
				
				
				+ "\tpublic Metadata createMetadata(String key,String value){%n"
				+ "\t\tMetadata md = new Metadata();%n"
				+ "\t\tmd.setObjectId(getId());%n"
				+ "\t\tmd.setObjectType(METADATA_TYPE);%n"
				+ "\t\tmd.setMetaKey(key);%n"
				+ "\t\tmd.setMetaValue(value);%n"
				+ "\t\treturn md;%n"
				+ "\t}%n%n";

		

		
		this.importTemplate = "import io.jpress.core.JModel;%n"
				+ "import io.jpress.model.Metadata;%n%n"
				+ "import java.util.List;%n%n"
				+ "import com.jfinal.plugin.activerecord.IBean;%n"
				+ "import com.jfinal.plugin.ehcache.CacheKit;%n%n";
		

	}

	@Override
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.baseModelName,
				tableMeta.baseModelName, tableMeta.name, tableMeta.name));
	}

}
