package io.jpress.core.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

import com.jfinal.plugin.activerecord.generator.ModelGenerator;
import com.jfinal.plugin.activerecord.generator.TableMeta;

public class JControllerGenerator extends ModelGenerator {

	public JControllerGenerator(String modelPackageName,
			String baseModelPackageName, String modelOutputDir) {
		super(modelPackageName, baseModelPackageName, modelOutputDir);
		
		this.importTemplate = "import io.jpress.core.annotation.UrlMapping;%n"
				+ "import io.jpress.model.%s;%n%n";
		
		this.classDefineTemplate =
				"/**%n" +
				" * Generated by JPress.%n" +
				" */%n" +
				"@UrlMapping(url = \"/admin/%s\", viewPath = \"/WEB-INF/admin/%s\")%n" +
				"public class _%sController extends BaseAdminController<%s> { %n%n";
		
		
		this.daoTemplate = "";
		
	}
	
	@Override
	protected void genImport(TableMeta tableMeta, StringBuilder ret) {
		// TODO Auto-generated method stub
//		super.genImport(tableMeta, ret);
		ret.append(String.format(importTemplate, tableMeta.modelName));
	}
	
	@Override
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.name,tableMeta.name,tableMeta.modelName,tableMeta.modelName));
	}
	
	public void generate(List<TableMeta> tableMetas) {
		System.out.println("Generate AdminController ...");
		for (TableMeta tableMeta : tableMetas)
			genModelContent(tableMeta);
		wirtToFile(tableMetas);
	}
	
	
	protected void wirtToFile(TableMeta tableMeta) throws IOException {
		File dir = new File(modelOutputDir);
		if (!dir.exists())
			dir.mkdirs();
		
		String target = modelOutputDir + File.separator + "_"+tableMeta.modelName + "Controller.java";
		
		File file = new File(target);
		if (file.exists()) {
			return ;	// 若 Model 存在，不覆盖
		}
		
		FileWriter fw = new FileWriter(file);
		try {
			fw.write(tableMeta.modelContent);
		}
		finally {
			fw.close();
		}
	}

		
		

}
