package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMetadata<M extends BaseMetadata<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Metadata:add";
    public static final String ACTION_DELETE = "Metadata:delete";
    public static final String ACTION_UPDATE = "Metadata:update";


    @Override
    protected String addAction() {
        return ACTION_ADD;
    }

    @Override
    protected String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    protected String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setObjectType(java.lang.String objectType) {
		set("object_type", objectType);
	}
	
	public java.lang.String getObjectType() {
		return getStr("object_type");
	}

	public void setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
	}
	
	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}

}
