package io.jpress.addon.message.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJpressAddonMessage<M extends BaseJpressAddonMessage<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 名字
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 名字
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 电话
     */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

    /**
     * 电话
     */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

    /**
     * 邮箱
     */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

    /**
     * 邮箱
     */
	public java.lang.String getEmail() {
		return getStr("email");
	}

    /**
     * 标题
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 留言内容
     */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 留言内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

    /**
     * 是否展示
     */
	public void setShow(java.lang.Boolean show) {
		set("show", show);
	}

    /**
     * 是否展示
     */
	public java.lang.Boolean getShow() {
		return get("show");
	}

}
