package io.jpress.module.crawler.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.crawler.model.base.BaseKeyword;

/**
 * Generated by Jboot.
 */
@Table(tableName = "c_keyword", primaryKey = "id")
public class Keyword extends BaseKeyword<Keyword> {
	
}
