package io.jpress.module.crawler.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.crawler.model.base.BaseKeywordCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "c_keyword_category", primaryKey = "id")
public class KeywordCategory extends BaseKeywordCategory<KeywordCategory> {
	
}
