package io.jpress.module.crawler.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.crawler.model.base.BaseSpider;

/**
 * Generated by Jboot.
 */
@Table(tableName = "c_spider", primaryKey = "id")
public class Spider extends BaseSpider<Spider> {
	
}
