package io.jpress.module.crawler.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.crawler.model.base.BaseWebpage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "c_webpage", primaryKey = "id")
public class Webpage extends BaseWebpage<Webpage> {
	
}
