package io.jpress.addon.message.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.message.model.base.BaseJpressAddonMessage;

/**
 * Generated by JPress.
 */
@Table(tableName = "jpress_addon_message", primaryKey = "id")
public class JpressAddonMessage extends BaseJpressAddonMessage<JpressAddonMessage> {

    private static final long serialVersionUID = 1L;

	
}
