package io.jpress.module.article.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticlePayRecord<M extends BaseArticlePayRecord<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setContentId(java.lang.Long contentId) {
		set("content_id", contentId);
	}
	
	public java.lang.Long getContentId() {
		return getLong("content_id");
	}

	public void setContentTitle(java.lang.String contentTitle) {
		set("content_title", contentTitle);
	}
	
	public java.lang.String getContentTitle() {
		return getStr("content_title");
	}

	public void setContentType(java.lang.Integer contentType) {
		set("content_type", contentType);
	}
	
	public java.lang.Integer getContentType() {
		return getInt("content_type");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setPaymentId(java.lang.Long paymentId) {
		set("payment_id", paymentId);
	}
	
	public java.lang.Long getPaymentId() {
		return getLong("payment_id");
	}

	public void setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
	}
	
	public java.lang.Integer getPaymentStatus() {
		return getInt("payment_status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
