package io.jpress.module.product.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jpress.base.BaseOptionsModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends BaseOptionsModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键ID
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * slug
     */
	public void setSlug(java.lang.String slug) {
		set("slug", slug);
	}

    /**
     * slug
     */
	public java.lang.String getSlug() {
		return getStr("slug");
	}

    /**
     * 标题
     */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

    /**
     * 内容
     */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

    /**
     * 摘要
     */
	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

    /**
     * 摘要
     */
	public java.lang.String getSummary() {
		return getStr("summary");
	}

    /**
     * 产品卖点
     */
	public void setUsp(java.lang.String usp) {
		set("usp", usp);
	}

    /**
     * 产品卖点
     */
	public java.lang.String getUsp() {
		return getStr("usp");
	}

    /**
     * 缩略图
     */
	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

    /**
     * 缩略图
     */
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

    /**
     * 样式
     */
	public void setStyle(java.lang.String style) {
		set("style", style);
	}

    /**
     * 样式
     */
	public java.lang.String getStyle() {
		return getStr("style");
	}

    /**
     * 排序编号
     */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

    /**
     * 排序编号
     */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

    /**
     * 商品价格
     */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

    /**
     * 商品价格
     */
	public java.math.BigDecimal getPrice() {
		return getBigDecimal("price");
	}

    /**
     * 原始价格
     */
	public void setOriginPrice(java.math.BigDecimal originPrice) {
		set("origin_price", originPrice);
	}

    /**
     * 原始价格
     */
	public java.math.BigDecimal getOriginPrice() {
		return getBigDecimal("origin_price");
	}

    /**
     * 限时优惠价（早鸟价）
     */
	public void setLimitedPrice(java.math.BigDecimal limitedPrice) {
		set("limited_price", limitedPrice);
	}

    /**
     * 限时优惠价（早鸟价）
     */
	public java.math.BigDecimal getLimitedPrice() {
		return getBigDecimal("limited_price");
	}

    /**
     * 状态
     */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

    /**
     * 评论状态，默认允许评论
     */
	public void setCommentStatus(java.lang.Boolean commentStatus) {
		set("comment_status", commentStatus);
	}

    /**
     * 评论状态，默认允许评论
     */
	public java.lang.Boolean getCommentStatus() {
		return getBoolean("comment_status");
	}

    /**
     * 评论总数
     */
	public void setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
	}

    /**
     * 评论总数
     */
	public java.lang.Long getCommentCount() {
		return getLong("comment_count");
	}

    /**
     * 最后评论时间
     */
	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}

    /**
     * 最后评论时间
     */
	public java.util.Date getCommentTime() {
		return getDate("comment_time");
	}

    /**
     * 访问量
     */
	public void setViewCount(java.lang.Long viewCount) {
		set("view_count", viewCount);
	}

    /**
     * 访问量
     */
	public java.lang.Long getViewCount() {
		return getLong("view_count");
	}

    /**
     * 销售量，用于放在前台显示
     */
	public void setSalesCount(java.lang.Long salesCount) {
		set("sales_count", salesCount);
	}

    /**
     * 销售量，用于放在前台显示
     */
	public java.lang.Long getSalesCount() {
		return getLong("sales_count");
	}

    /**
     * 购买链接
     */
	public void setBuyLink(java.lang.String buyLink) {
		set("buy_link", buyLink);
	}

    /**
     * 购买链接
     */
	public java.lang.String getBuyLink() {
		return getStr("buy_link");
	}

    /**
     * 视频ID
     */
	public void setVideoId(java.lang.String videoId) {
		set("video_id", videoId);
	}

    /**
     * 视频ID
     */
	public java.lang.String getVideoId() {
		return getStr("video_id");
	}

    /**
     * 创建日期
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

    /**
     * 最后更新日期
     */
	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

    /**
     * 最后更新日期
     */
	public java.util.Date getModified() {
		return getDate("modified");
	}

    /**
     * 标识，通常用于对某几个商品进行标识，从而实现单独查询
     */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

    /**
     * 标识，通常用于对某几个商品进行标识，从而实现单独查询
     */
	public java.lang.String getFlag() {
		return getStr("flag");
	}

	/**
	 * SEO标题
	 */
	public void setMetaTitle(java.lang.String metaTitle) {
		set("meta_title", metaTitle);
	}

	/**
	 * SEO标题
	 */
	public java.lang.String getMetaTitle() {
		return getStr("meta_title");
	}

	/**
     * SEO关键字
     */
	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

    /**
     * SEO关键字
     */
	public java.lang.String getMetaKeywords() {
		return getStr("meta_keywords");
	}

    /**
     * SEO描述信息
     */
	public void setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
	}

    /**
     * SEO描述信息
     */
	public java.lang.String getMetaDescription() {
		return getStr("meta_description");
	}

    /**
     * 备注信息
     */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

    /**
     * 备注信息
     */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

    /**
     * json 扩展
     */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}

    /**
     * json 扩展
     */
	public java.lang.String getOptions() {
		return getStr("options");
	}

    /**
     * 站点ID
     */
	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

    /**
     * 站点ID
     */
	public java.lang.Long getSiteId() {
		return getLong("site_id");
	}

}

