package io.jpress.module.article.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.article.model.base.BaseArticleCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_category", primaryKey = "id")
public class ArticleCategory extends BaseArticleCategory<ArticleCategory> {
	
}
