package io.jpress.module.article.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.article.model.base.BaseArticleCategoryMapping;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_category_mapping", primaryKey = "article_id,category_id")
public class ArticleCategoryMapping extends BaseArticleCategoryMapping<ArticleCategoryMapping> {
	
}
