package io.jpress.module.article.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.article.model.base.BaseArticlePayRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_pay_record", primaryKey = "id")
public class ArticlePayRecord extends BaseArticlePayRecord<ArticlePayRecord> {
	
}
