package io.jpress.module.article.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.article.model.base.BaseArticleComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_comment", primaryKey = "id")
public class ArticleComment extends BaseArticleComment<ArticleComment> {
	
}
