package io.jpress.addon.articlemeta.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.articlemeta.model.base.BaseArticleMetaInfo;
import io.jpress.core.ext.field.SmartField;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_meta_info", primaryKey = "id")
public class ArticleMetaInfo extends BaseArticleMetaInfo<ArticleMetaInfo> {

    /**
     * 默认的排序值
     */
    private static final int DEFAULT_ORDER_NUMBER = 100;

    public SmartField toSmartField() {
        SmartField smartField = new SmartField();
        smartField.setOrderNo(getOrderNo() == null ? DEFAULT_ORDER_NUMBER : getOrderNo());
        smartField.setAttrs(getAttrs());
        smartField.setHelpText(getHelpText());
        smartField.setId(getFieldId());
        smartField.setName("articleMeta." + getFieldName());
        smartField.setLabel(getLabel());
        smartField.setPlaceholder(getPlaceholder());
        smartField.setType(getType());
        smartField.setValue(getValue());
        smartField.setValueText(getValueText());
        return smartField;
    }


}
