package io.jpress.addon.articlemeta.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.articlemeta.model.base.BaseArticleMetaInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article_meta_info", primaryKey = "id")
public class ArticleMetaInfo extends BaseArticleMetaInfo<ArticleMetaInfo> {
	
}
